### ISSUE TITLE
FRI must sample unique locations in each round

### ISSUE THREAD

**Issue by Sword-Smith** [Sword-Smith/twenty-first#12]
Our current FRI implementation probes non-unique locations and points can thus be repeated in each round. They must all be unique so the set of remaining locations must be remembered and the next chosen point must be sampled from there. If there are not enough unique points left, the FRI iterator must stop and return the final codeword which may not be constant but could be of degree e.g. 8. The verifier must verify that this last codeword has the expected degree.

**Comment by Sword-Smith** [comment]
In the last step, we check the degree of the polynomial with a slow (non-NTT) interpolation method. To do this, we need the points of the last codeword, but we only have the y values. I think we can find the equivalent x values from the x-values of the `a` points and then square these. That's what my intuition tells me.

But it would be nice if @aszepieniec could confirm my derivation.

**Comment by aszepieniec** [comment]
The x-values should be `{ omega^(2^k + i) | i in [0 : codeword_length) }` where `k` is the number of split-and-folds that have taken place. Test that this sequence starts with a `1` and does not have `1`'s anywhere else and that `omega^(2^k+codeword_length) == 1`.
