### ISSUE TITLE
`slow_lagrange_interpolation` has a bad signature

### ISSUE THREAD

**Issue by Sword-Smith** [Sword-Smith/twenty-first#16]
This function for `Polynomial` structs has a function `pub fn slow_lagrange_interpolation(points: &[(U, U)]) -> Self`. Instead of taking a slice of tuples, it should accept to slices, one for x-values and one for y-values, as this is often how we have the values in the caller.

**Comment by sshine** [comment]
Solved in 7fceb2d61500d8830cebf9c02951170381f58cc6.
