### ISSUE TITLE
Add benchmarking

### ISSUE THREAD

**Issue by Sword-Smith** [Sword-Smith/twenty-first#3]
Follow this guide to add benchmarking functionality for this repo
http://seenaburns.com/benchmarking-rust-with-cargo-bench/

**Comment by Sword-Smith** [comment]
Cf. this guide, I can only run the `cargo bench` command if I change from the `stable` to the `nightly` `rustc` compiler version. I don't think I want to do that.

**Comment by Munksgaard** [comment]
Closed by #4
