### ISSUE TITLE
Use NTT to evaluate and interpolate polynomials

### ISSUE THREAD

**Issue by Sword-Smith** [Sword-Smith/twenty-first#7]
Our current algorithms for polynomial interpolation and evaluation for multiple points are not asymptotically optimal as they have quadratic runtimes. With NTT, we can go from quadratic rumtimes to `Nlog(N)` runtimes.

**Comment by aszepieniec** [comment]
Fast interpolation/batch-evaluation on domains that correspond to subgroups of order 2^k of the field are straightforward. Fast batch-evaluation on domains that correspond to a contiguous segment (=generator raised to an interval of integers) of such a subgroup is straightforward as well, but fast interpolation on these segments requires some exciting maths. (But still possible.)
